language: python
python:
    - "3.4"
    - "3.5"
    - "3.5-dev" # 3.5 development branch
    - "3.6-dev" # 3.6 development branch
    - "nightly" # currently points to 3.7-dev

matrix:
    allow_failures:
        - python: nightly

dist: trusty
sudo: required
addons:
  apt:
    packages:
      - git
      - cmake

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

# install libgit2
before_install:
    - "./.travis.sh"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls

# command to run tests
script:
    - coverage run -a --source=quit tests/test_core.py
    - coverage run -a --source=quit tests/test_conf.py
    - coverage run -a --source=quit tests/test_app.py

after_success:
    coveralls
