language: python
python:
    - "3.4" # debian jessie, lts 2020-04
    - "3.5" # debian stretch, lts 2022-06
    - "3.6" # debian buster, testing as of 2018-09
    - "3.7-dev" # 3.7 development branch
    - "nightly"

matrix:
    allow_failures:
        - python: "3.7-dev"
        - python: "nightly"

dist: trusty
sudo: required
addons:
  apt:
    packages:
      - git
      - cmake
      - libssl-dev
      - libssh2-1-dev

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

# install libgit2
before_install:
    - "./.travis.sh"

# command to install dependencies
install:
    - pip install -U setuptools
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pylava

before_script:
    - "pylava"

# command to run tests
script:
    - coverage run -a --source=quit tests/test_app.py
    - coverage run -a --source=quit tests/test_cache.py
    - coverage run -a --source=quit tests/test_conf.py
    - coverage run -a --source=quit tests/test_core.py
    - coverage run -a --source=quit tests/test_endpoint.py
    - coverage run -a --source=quit tests/test_git.py
    - coverage run -a --source=quit tests/test_graphs.py
    - coverage run -a --source=quit tests/test_helpers.py
    - coverage run -a --source=quit tests/test_namespace.py
    - coverage run -a --source=quit tests/test_provenance.py

before_deploy:
  - pyinstaller -F quit.spec
  - cp dist/run dist/quit

deploy:
  provider: releases
  api_key:
    secure: lvGR9nWYc/FI98SIGwRaTXXqjcL1hVDMc/P4W4Tg8gdNQ3LSJ4yYzYdtLOfqOupwUxFKR3//mzYbxBEIxXADNos9QtN5scVdZyiApG+FjYRa4TS/JkQ5tk4/aIjlCdwiUOAM9hKfclO7QmWcUX9xtagBG+Z9f99Xm4Z2gzmlq6+bnD4r/ODm8j3AbyHGq3vRNeuz9CiMxgwTTsOaP738BynmOdAVlL0YNw/Rjt1E6xTfjJ0zGT2CYDqUgA/A/RagrMZnESo/2htzQ2G7cYhv6txvCg2pCP2VIiubTni/cC1h3eTPledbmoePdtd9xHA9xb2WSB4RSBeYBr3DTJIrysTDyUOFhI2L/UHFwXlH1UlQZCaRzf/+cIHvoQPxs6PC1mZHs/SgPm+4m1OoJwrXsAMgn52cvVbM7WIhIWYxtQYshDKCip3XQa8ybzn0bVPNi2/zsl+yKdS1PKzeoNxeoBXExyK3igTXKs+u2He8s97wJZII9C+n2GbK/ndqwOENUDOVKuVytmBJ372XrvBLcxS41dMtX/AnFcr+P6ZCZ+PI71D1+GG+pU7KNglyI2RQPBlWfSOM00bXQ16HDYaWD/ktoDVYaj4YkenxFEMoRYyirHw6fFwXRWHZCCg1CA29EIU+HD3kQXzwmxtoecc9zhFpW5WHYUn9DiKdwq6A9xg=
  file: dist/quit
  skip_cleanup: true
  on:
    condition: $TRAVIS_PYTHON_VERSION = 3.6
    tags: true
    repo: AKSW/QuitStore

after_success:
    coveralls debug
