[tool.poetry]
name = "quit"
version = "0.25.4"
description = "Quads in Git - Distributed Version Control for RDF Knowledge Bases"
authors = ["Norman Radtke <http://aksw.org/NormanRadtke>", "Natanael Arndt <http://aksw.org/NatanaelArndt>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
